spine_params:
  dt_fat_lookback_window: 90 #dias
  #diferença de dias permitido entre data do pedido e do faturamento, sendo pedido > faturamento
  dt_fat_pedido_diffdays: 30
  # quantidades de dias para considerar os pedidos no cálculo da mediana
  # apenas para pedidos onde não há faturamento, é um dado fake para considerar os pedidos de label "não_compra"
  qtd_dias_lookback_pedidos: 1095 #3 anos (3*365)

clientes_params:
  cultura: "laranja"
