spine_params:
  # quantidade de dias para considerar os dados de mercado olhando para trás e para frente (projeção) a partir do faturamento
  dt_fat_lookback_window: 730 #2 anos (2*365)
  dt_fat_lookforward_window: 365 #1 ano (1*365)
  #diferença de dias permitido entre data do pedido e do faturamento, sendo pedido > faturamento
  dt_fat_pedido_diffdays: 30
  # quantidades de dias para considerar os pedidos no cálculo da mediana
  # apenas para pedidos onde não há faturamento, é um dado fake para considerar os pedidos de label "não_compra"
  qtd_dias_lookback_pedidos: 1095 #3 anos (3*365)

clientes_params:
  cultura: "laranja"

master_table_params:
  treino_teste_split:
    shuffle: true #bool: true or false
    train_size: 0.7
    random_state: 42
    stratify: true #bool: true or false

  target_col: "label" #nome da coluna target

  # limites inferir e superior para balancear as classes
  # se estiver fora do range, então está desbalanceado
  class_bounds:
    lower: 0.45 #percent
    upper: 0.55 #percent

  vif_limite: 10 #valor limite para o vif
  slc_topN_features: 20 #quantidade de features a serem selecionadas

# se `model_params_otimizar` é true, então os parâmetros serão otimizados em run time
logreg_params:
  model_params_otimizar: false
  # utilizar esses parâmetros independentemente de otimização
  model_params_padrao:
    n_jobs: -1
  # se `optimize_params` é false, então usa esses parâmetros
  model_params_extra:
    solver: "saga"
    penalty: "elasticnet"
    tol: 0.001
    C: 1.0
    max_iter: 200
    fit_intercept: true
    class_weight: "balanced"
    l1_ratio: 0.1
